import "~/styles/globals.css";

import { Montserrat } from "next/font/google";

import Header from "./_components/sections/header";

import { type Metadata } from "next";
import FooterSection from "./_components/sections/FooterSection";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const font = Montserrat({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${font.className}`}>
      <body>
        <Header />
        {children}
        {/* <footer className="bg-primary text-white"> */}
        <FooterSection />
      </body>
    </html>
  );
}
